CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    name       VARCHAR(50)                               NOT NULL,
    email      VARCHAR(50)                               NOT NULL,
    country    VARCHAR(50)                               NOT NULL,
    age        INTEGER                     DEFAULT null  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);